[package]
name = "pg"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8.0", features = ["runtime-tokio", "runtime-tokio-rustls", "postgres", "derive", "uuid", "json"] }
tokio = { version = "1.39.2", features = ["full"] }
